FROM resin/raspberry-pi-python:3

WORKDIR /var/lib/fd-edge

COPY . .

RUN pip install --upgrade pip

RUN pip3 install image
RUN pip3 install opencv-python-headless

RUN mkdir images
RUN mkdir greyImages

ENV PYTHONPATH=/var/lib/fd-edge

CMD ["python3","2grey.py"]