#FROM arm32v7/python:3.6-buster
FROM balenalib/raspberrypi3-debian-python:latest
WORKDIR /var/lib/fd-edge-send

COPY . .

RUN mkdir greyImages

ENV PYTHONPATH=/var/lib/fd-edge-send

ENTRYPOINT python3 edgeSend.py